rancher-server:
  image: rancher/server:v1.3.0
  restart: unless-stopped
  volumes_from:
    - pinpoint-agent
  ports:
    - 8080:8080
  environment:
    JAVA_OPTS: "-javaagent:/assets/pinpoint-agent/pinpoint-bootstrap-1.6.2.jar -Dpinpoint.agentId=app-in-docker -Dpinpoint.applicationName=app"

pinpoint-agent:
  image: wahyd4/pinpoint-agent:1.6.2
  net: "none"
  restart: unless-stopped
#  volumes:
#    - /var/container_data/pinpoint-agent/log:/opt/app/pinpoint-agent/log:rw
  environment:
    COLLECTOR_IP: 192.168.99.100
    COLLECTOR_TCP_PORT: 9994
    COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
    COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
    DISABLE_DEBUG: 'true'
